### ISSUE TITLE
support harmony proxies

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/mongojs#134]
This will allow us to use it like this:

``` js
var db = mongojs('my-db');
db.foobar.findOne(function() {
   // foobar collection object is automatically created on first get
   ...
});
```

**Comment by Anagmate** [comment]
Don't know why, the code looks solid, but on my PC (node 0.12.2, mongoDb 3.0.5, mongoJs 1.3.0), getter doesn't trigger at all (tried adding console.log to get method in Proxy.create, no output)). Strange thing is, when I cut out requires and db init (https://gist.github.com/Anagmate/074800a06bdc285d84f7), it worked.
