### ISSUE TITLE
error parsing elemeng 0 of field documents

### ISSUE THREAD

**Issue by KnowledgeGarden** [mafintosh/mongojs#141]
I get this error when storing a JSON string (included in the error message):

error parsing element 0 of field documents :: caused by :: wrong type for '0' field, expected object, found 0: "{"locator":"MyTestProxy","instanceOf":"FancyNode","subOf":["MySuper"]}" undefined

I did not start seeing that error till I upgraded to MongoDB 2.6.1; prior to that, documents were stored but capable of being fetched.  The JSON string is crafted in a class with a properties map using JSON.stringify on that map.

From web searching, it's not even clear what a "field document" is, and it's not at all clear where the '0' came from, unless this helps:
In prior testing with older mongo, I could do a find() on the collection and get back an object based on the same class result. Printing that object in console.log returned this (truncated):
{ '0': '{',
  '1': '"',
  '2': 'l',
  '3': 'o',
  '4': 'c',
Now, the actual query string sent into save looks like  "{"locator":"MyTestProxy","in..... but I get back what looks like a numbered array of individual characters.  That error doesn't google well.

Looking forward to learning what I am missing.

**Comment by saintedlama** [comment]
Outdated
