### ISSUE TITLE
How to check connection error in mongojs

### ISSUE THREAD

**Issue by rohittailor** [mafintosh/mongojs#149]
Hi,

How to  check connection error in mongojs. When we run the app and mongodb is up than its working fine. When we stop mongodb, it throws an exception. Can we handle connection errors in mongojs ?

**Comment by bluedusk** [comment]
Hi , I ran into this same problem with mongojs 1.3.0 on Windows 7 , I cant get any event when mongodb is not running or when I stop it. 
```
var mongojs = require('mongojs');
var db = mongojs('test', ['a']);

db.on('error', function() {
  console.log('we had an error.');
});
```

**Comment by Sparragus** [comment]
I have the same issue as @bluedusk. If I don't have a mongodb server running, the app simply fails silently and exits. It should emit the `error` event or throw. It does neither.

Specs:
OSX 10.10.5
node v2.2.1
mongojs 1.3.0
mongodb v3.0.6

**Comment by sergiolc** [comment]
I have the same issue as @Sparragus.

mongojs 1.3.0

**Comment by julio-coelho** [comment]
Same here. If the server was not running on the connection, no error is thrown.
A callback function would be nice.

**Comment by julianusti** [comment]
same here.

**Comment by rafajaw** [comment]
Is it going to be fixed? it's a showstopper for me. I saw some topic saying to use a connectionTimeout parameter like this:
```javascript
var db  =  mongojs( db_conn, ['bots'], {connectionTimeout: 3000} );
db.on('timeout', function (err) {
    console.log('database timeout');
});
```
but it is still **not working**.

**Comment by iMoses** [comment]
Nothing worse than finding the issue you're struggling with in github only to discover it should have been fixed a year ago :)

**Comment by saintedlama** [comment]
In version 2.0.0 you can register an error event listener with 
```js
var db  =  mongojs( db_conn, ['bots'], {connectionTimeout: 3000} );
db.on('error', function (err) {
    console.log('Connection errored', err);
});
```

**Comment by amado-saladino** [comment]
That did not work for me, it throws the error and logged (app crashed)
