### ISSUE TITLE
Rewrite using mongodb-core

### ISSUE THREAD

**Issue by sorribas** [mafintosh/mongojs#157]
So, this is a big one, but @christkv published a module called `mongodb-core` aimed at library writers rather than users and it offers a nicer API for this purpose than what we are using right now which is the driver. So we want to rewrite the module using this.

https://github.com/christkv/mongodb-core

**Comment by prabhu** [comment]
Any updates on this? Looks like 2.0 native driver has many compatibility breaking changes. Rewrite using mongodb-core is probably a good idea to support the upcoming 2.8 release

**Comment by sorribas** [comment]
Hey @prabhu I've been a bit busy but I plan to retake work on this for tomorrow. There's a branch called `mongodb-core` you can check the advances there. As of now I have completed all the cursor methods and have a bit over half of the collection methods. After this we only miss a couple of collection methods and the connection string parser, that I plan to use from the mongodb driver.

**Comment by prabhu** [comment]
Thanks for the update. Looking forward for the release.

**Comment by saintedlama** [comment]
@sorribas shall I close the issue since migrating to mongodb-core is done :+1:
