### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by huzhifeng** [mafintosh/mongojs#158]
I'm trying to set password for mongodb to prevent access to any db with empty login and pass (set by default).

Before starting the mongodb with authentication, I created a user `admin` in database `admin` to enable global authentication. Then restart the mongod with `--auth`

```
user admin;
db.addUser('admin', 'admin');
```

There are some databases on mongodb, and my project want to connect to database `todo`, so my code is like this:

```
db = mongojs('admin:admin@localhost:27017/todo');
```

But I saw auth failure:

```
Sat Nov 08 20:49:10 [conn23] auth: couldn't find user admin, todo.system.users
```

It looks like verified the account in `todo.system.users` instead of `admin.system.user`

I want to do global authentication before connect to specific database.
How to do this?
Thanks.

**Comment by dilignt** [comment]
I'm unable to get this to work.  With the following web user I can show collections in the test database

```
$ mongo
MongoDB shell version: 3.2.0
connecting to: test
> use admin
switched to db admin
> db.auth('web', 'k1ll3r5')
1
> use test
switched to db test
> show collections
store
>
```
But when I try to do the equivalent using this code with mongojs with  the `authSource` option
```
var mongojs = require('mongojs');

var db = mongojs('web:k1ll3r5@localhost/test?authSource=admin');

db.getCollectionNames(function(err, names) {
    console.log(arguments);
});
```
it won't authenticate
```
{ '0':
   { [MongoError: auth failed]
     name: 'MongoError',
     message: 'auth failed',
     ok: 0,
     errmsg: 'auth failed',
     code: 18 } }
```
What am I doing wrong? 
many thanks
