### ISSUE TITLE
Find by _id

### ISSUE THREAD

**Issue by dezinezync** [mafintosh/mongojs#16]
I am fairly new to mongodb and just started using mongojs in my nodejs app. 

I wish to find items using their _id. 

I tried 
`db.abc.find({_id: req.params.id}, function(...) {  ...  })`
&
`db.abc.find({_id: "ObjectId("+req.params.id+")"}, function(...) {  ...  })`

Either of them did not work. Can this be achieved?

**Comment by lxdyran** [comment]
Thanks! It really helps!
