### ISSUE TITLE
won't emit events when do nothing with mongo

### ISSUE THREAD

**Issue by longbill** [mafintosh/mongojs#162]
``` js
var mongojs = require('./');
var db = mongojs('mongodb://localhost:27017/router', ['pv_hour']);

db.on('error', function(err) {
  console.log('OH NOES!', err);
});

db.on('ready',function()
{
    console.log('mongodb connected');
});
```

the code above will never show anything in console

**Comment by saropatzi** [comment]
May i suggest to add the db.open() line to the "event" section of the guide. As it is now it's the suggested code is confunsing (especially if it's your first try with mongojs) ^^
