### ISSUE TITLE
How can we use hint in find/update query?

### ISSUE THREAD

**Issue by nai0om** [mafintosh/mongojs#163]
I have tried to use to use hint like http://docs.mongodb.org/manual/reference/operator/meta/hint/ but it seems not work to me.

**Comment by bradvogel** [comment]
This doesn't appear to work in the latest mongojs (2.3.0). "MongoError: unknown top level operator". Any ideas?

**Comment by saintedlama** [comment]
@bradvogel could you post a code snippet that does not work? What version of mongojs are you using?

**Comment by bradvogel** [comment]
Figured it out - the hint() method works.
