### ISSUE TITLE
Error when no callback is used with bulk.execute()

### ISSUE THREAD

**Issue by goldfire** [mafintosh/mongojs#166]
I get the following error when calling `bulk.execute()` without a callback:

    TypeError: undefined is not a function

This error references where the callback tries to execute in mongodb-native at https://github.com/mongodb/node-mongodb-native/blob/V1.4.19/lib/mongodb/collection/batch/unordered.js#L382.

**Comment by sorribas** [comment]
Thanks! Nice catch. Fixed in `0.18.1`
