### ISSUE TITLE
Relationships / dbrefs supported?

### ISSUE THREAD

**Issue by nexflo** [mafintosh/mongojs#167]
the doc doesnt say?

**Comment by sorribas** [comment]
There is currently no support for de-referencing dbrefs. You can construct a query yourself, but I guess that's not what you're looking for. I also don't know if that's something we want to add for the module. Would like to hear @mafintosh 's opinion on this.

**Comment by saintedlama** [comment]
@sorribas the de-referencing thingy only creates an opaque interface for a functionality that leads to SELECT N+1 problems in the end.
