### ISSUE TITLE
Processing from standalone process

### ISSUE THREAD

**Issue by KrzysztofMadejski** [mafintosh/mongojs#168]
Hi,

I'm wondering how to properly initialize connection and process data in standalone process. I'm starting to communicate with mongo after receiving 'ready' event, so I'm sure everything is properly initialized. 

The problem is my node process exits before I'm able to query anything. Is there any `db.wait()` I'm missing below? Shoudn't node wait till all connections are closed?

```coffee
db = mongojs(config.mongo_connection, ['user'])

db.on 'ready', () ->
    # may not get executed because process finishes
    console.log('database connected');
    db.user.findOne()
```

**Comment by KrzysztofMadejski** [comment]
Maybe http://stackoverflow.com/a/8636001/803174?

**Comment by mafintosh** [comment]
don't wait for `ready`. just execute your `findOne` right away.

``` js
db = mongojs(...)
db.user.findOne(function(err, data) {
  console.log('got data', err, data)
})
```

**Comment by KrzysztofMadejski** [comment]
Ok. I've thought it can result in error if connection won't be established by then. 
So if I understand right creating connection with `db = mongo(...)` is synchronous and will result in fully initialized `db`?

**Comment by sorribas** [comment]
It is not synchronous, but the database is lazy evaluated, which means that it will try to connect at the time the first operation is attempted.

**Comment by KrzysztofMadejski** [comment]
Ok, thank you!
