### ISSUE TITLE
Way to wait until call finishes?

### ISSUE THREAD

**Issue by charliemc** [mafintosh/mongojs#169]
Hi,

I am new to `node.js` and `mongodb` and I'm trying to implement some functionality in which I want to save a bunch of docs into a couple of collections, and get those docs later to do some stuff with them. I was wondering how could I call synchronously some of these mongojs methods. I'll explain this:

- I have implemented a module called `Mongo` which exports some functions. One of this module's function called `getDocuments()` calls **mongojs** `db.collection.find( {} )` function and returns all the docs inside the collection.
- In another module, I need to define a variable to save that collection array. After that, I will do some stuff with that array:

```
// requiring my module
var Mongo = require("./my_mongo_module");
var mongo =  new Mongo();

...

var myDocs = mongo.getDocuments();
// do stuff here with myDocs...
```

How can I get to execute the code below`mongo.getDocuments()` only after I got all the docs? I guess this way `db.collection.find({})` is being executed asynchronously... Am I right? How could I just wait until  `db.collection.find({})` returns something?

Thank you in advanced.

**Comment by sorribas** [comment]
Node.js is asynchronous by nature so what you want cannot be done. You have to add a callback to the getDocuments function that gets called with the docs so you can do stuff like this.

```js
mongo.getDocuments(function(err, myDocs) {
  // do stuff here with myDocs...
});
```
