### ISSUE TITLE
Wrong count of collection

### ISSUE THREAD

**Issue by fawad1985** [mafintosh/mongojs#172]
When I write the following command:
db.collection.runCommand('count', function(err, res) {
    	console.log(res);
});

I get the this result
{ n: 390, ok: 1 }

However, when I connect to Mongo shell and write the following command:

db.collection.find().count()

I get 471

Does anyone have an idea what could be the problem?

**Comment by prabhu** [comment]
Which mongodb version are you using? From node_modules. I am doubting that there is some issue with the listCollections method in mongodb native.

This bug could be related to this - https://jira.mongodb.org/browse/NODE-352

**Comment by fawad1985** [comment]
Thanx Prabhu for your prompt answer. I am using Mongo 2.6, the bug is really weird and I am still trying to understand it.

**Comment by prabhu** [comment]
Feels like we need to test listCollections a bit thoroughly. I am not convinced the refactoring that they did for 1.4.20 is good enough.

**Comment by prabhu** [comment]
1.4.30 is out now including bug fixes to list collections. I have updated my repo and submitted a PR to @mafintosh

**Comment by fawad1985** [comment]
Thanx! I will give it a look :)

**Comment by saintedlama** [comment]
Outdated
