### ISSUE TITLE
Sporadic Uncaught unspecified error events

### ISSUE THREAD

**Issue by 5an1ty** [mafintosh/mongojs#173]
/myapp/node_modules/mongojs/node_modules/mongodb/lib/mongodb/mongo_client.js:460
              throw err
                    ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at emit (events.js:74:15)
    at /myapp/node_modules/mongojs/index.js:618:14
    at /myapp/node_modules/mongojs/node_modules/mongodb/lib/mongodb/mongo_client.js:457:15
    at process._tickCallback (node.js:419:13)

**Comment by prabhu** [comment]
Do you have any test case or scenario to trigger this?

**Comment by 5an1ty** [comment]
I wrote an application that runs all the time and writes to mongodb every couple of seconds, it will run fine for hours/days and then once in a while crash with the following error. I wish I had a way to replicate this but unfortunately, I have no clue what is causing it to pop up. It's really frustrating tho...
