### ISSUE TITLE
maxTimeMS support

### ISSUE THREAD

**Issue by mattdodge** [mafintosh/mongojs#174]
Since MongoDB version 2.6, cursors can supply a maximum execution time. A function wrapper for this would be useful.

http://docs.mongodb.org/manual/reference/operator/meta/maxTimeMS/

That doc claims you can include `$maxTimeMS` in the projection of the `find()` call but I'm unable to confirm that, even using just the mongo shell. Regardless, a cursor method would probably be useful.

**Comment by prabhu** [comment]
Looks like mongodb-core doesn't support maxTimeMS yet. Ask @christkv directly - https://github.com/christkv/mongodb-core

**Comment by christkv** [comment]
mongocore does :) just take a look at how the 2.0 driver passes it through to mongodb-core

**Comment by prabhu** [comment]
Sorry was looking in the wrong place.

**Comment by prabhu** [comment]
Phew, this took a bit of time but finally available on typescript version mongots - https://github.com/prabhu/mongots/commit/5f1337158260b13258905ddf8814499620a8ab6d

Will send a bunch of PR next week for the js version
