### ISSUE TITLE
Can't get mongojs to work with SSL.

### ISSUE THREAD

**Issue by rambler** [mafintosh/mongojs#179]
Is there a path to getting mongojs to work with SSL?

**Comment by sorribas** [comment]
We use it in production with SSL. You can do it like this

```js
var db = mongojos('somemongoserver.com/mydb?ssl=true');
```

**Comment by rambler** [comment]
Is there a way to supply a client certificate?

**Comment by matthiasdg** [comment]
Having the same problem, don't think this is possible since there is no way to provide sslCert or sslKey parameters in a connection string (see http://docs.mongodb.org/manual/reference/connection-string/).
Working fine using node-mongodb-native

**Comment by Stellaverse** [comment]
Has this been resolved? What was the outcome? I'm looking to do this myself right now and not sure how I should proceed.

**Comment by saintedlama** [comment]
Fixed. See #221 for usage with client certs
