### ISSUE TITLE
Error in insert() documents when write concern is 0 {w:0}

### ISSUE THREAD

**Issue by 4kochi** [mafintosh/mongojs#181]
`Fatal error: Cannot read property '0' of null`

The problem is this code: 

```js
Collection.prototype.insert = function() {
  var args = arguments;
  var fn = getCallback(arguments);

  var callback = function(err, docs) {
    if (err) return fn(err);
    if (Array.isArray(args[0])) {
      fn(err, docs, { n : 0});
    } else {
      // docs is null when write concern is 0
      fn(err, docs[0], { n : 0});
    }
  };
  this._apply(DriverCollection.insert, replaceCallback(arguments, callback));
};
```

You can avoid it by changing one line:

```js
fn(err, docs === null ? null : docs[0], { n : 0});
```

P.S.
I tried to create a pull request, but i didn't get the test to run. I use io.js 1.4.1 and MongoDB 3.0.0-rc11. Seems like mongojs is not compatible with this combination.

**Comment by prabhu** [comment]
The latest collection.js code in master no longer supports write options :( It's hard coded to a default value.

**Comment by prabhu** [comment]
I have added write concern support to mongots - https://github.com/prabhu/mongots/commit/5868cecb25f217084e7b812af9917a1176dcd5fd (Just loving typescript!)

I will redo this for mongojs and send a PR later

**Comment by 4kochi** [comment]
Yes, i have test the v1.0.0-beta3 and still get an error. But this time the problems is that the callback is always called. By in my case there is no callback. So a simple check if the callback exists would do the trick.
