### ISSUE TITLE
bulk.tojson()

### ISSUE THREAD

**Issue by cc-lam** [mafintosh/mongojs#184]
First, thanks for this great mongo driver.

bulk.execute throws an exception when there are no operations to execute.  It is a problem because unless I'm mistaken, bulk.tojson() is not implemented, which means it is impossible to check for the number of operations in the bulk op and bulk.execute() needs to always be wrapped inside a try/catch

**Comment by saintedlama** [comment]
In versions 1.0.x `bulk.tojson` function is implemented.
