### ISSUE TITLE
Several calls on insert; only the first one is stored.

### ISSUE THREAD

**Issue by carloschida** [mafintosh/mongojs#187]
# Set Up
With an http server, I want to store a document using insert. The code in `test.js` is the following:

```javascript
var http = require('http'),
	mongojs = require('mongojs');

// Connect to the db.
var uri = "...",
	db = mongojs.connect(uri, ["tweets"]);
db.on('error',function(err) {
    console.log('database error', err);
});
db.on('ready',function() {
    console.log('database connected');
});

var sentiments = [{
					phrase: 		'',
					tweets: 		0,
					totalsentiment:	0
				}];

function requestHandler(request, response) {
	response.writeHead(200, { "Content-Type": "text/html" });
	db.tweets.insert(sentiments[0], function (err, records) {
		if (err) {
			console.error("Document could NOT be inserted.");
			response.write("<h1>Not Saved</h1>");
			response.end();
	    	return;
		}
		console.log("Record added as " + records);
		response.write("<h1>Saved</h1>");
		response.end();
	});
}

var server = http.createServer(requestHandler);

// Run
console.log('Server listening on port 8888.');
server.listen(8888);
```

# Console

The output in the console for **a single** http request (browser) after executing `node test.js` the following:

>Server listening on port 8888.
>database connected
>Record added as undefined
>Document could NOT be inserted.
>Document could NOT be inserted.

Note that the second line `database connected` is only shown after this request. Given that the event is declared on the 10th line of `test.js` I expected it to appear right after the code is executed.

For **every** other request I make the last line `Document could NOT be inserted.` **appears 3 times**.

# mongod

On the deamon the following log is shown after the request:

>2015-04-07T16:09:53.036+0200 [initandlisten] connection accepted from 127.0.0.1:56403 #43 (1 connection now open)
>2015-04-07T16:09:53.037+0200 [initandlisten] connection accepted from 127.0.0.1:56404 #44 (2 connections now open)
>2015-04-07T16:09:53.037+0200 [initandlisten] connection accepted from 127.0.0.1:56405 #45 (3 connections now open)
>2015-04-07T16:09:53.038+0200 [initandlisten] connection accepted from 127.0.0.1:56406 #46 (4 connections now open)
>2015-04-07T16:09:53.039+0200 [initandlisten] connection accepted from 127.0.0.1:56407 #47 (5 connections now open)
>2015-04-07T16:09:53.047+0200 [conn43]  authenticate db: mongodb-sentiment { authenticate: 1, user: "carloschida", nonce: "xxx", key: "xxx" }
>2015-04-07T16:09:53.048+0200 [conn44]  authenticate db: mongodb-sentiment { authenticate: 1, user: "carloschida", nonce: "xxx", key: "xxx" }
>2015-04-07T16:09:53.048+0200 [conn45]  authenticate db: mongodb-sentiment { authenticate: 1, user: "carloschida", nonce: "xxx", key: "xxx" }
>2015-04-07T16:09:53.048+0200 [conn46]  authenticate db: mongodb-sentiment { authenticate: 1, user: "carloschida", nonce: "xxx", key: "xxx" }
>2015-04-07T16:09:53.049+0200 [conn47]  authenticate db: mongodb-sentiment { authenticate: 1, user: "carloschida", nonce: "xxx", key: "xxx" }

# Questions
1. Why is log of the event on 'ready' only displayed after the http request is made?
2. Why is the insert call in `requestHandler` being called 3 times for every http request?
3. Why does every insert call after the first one fail?

Thank you very much for your help.

**Comment by prabhu** [comment]
1. I am guessing its a feature of thunky (https://github.com/mafintosh/thunky) which the driver uses. I think the connection is getting delayed.
2. Your browser might be making multiple calls such as for favicon.ico etc even if you are knowingly requesting only one url
3. Can you print the err as well. That will give you the answer

**Comment by carloschida** [comment]
Just added `console.log(err);` after `console.error("Document could NOT be inserted.");`. The console looks like this now:

>database connected
>Record added as [object Object]
>Document could NOT be inserted.
>{ [MongoError: E11000 duplicate key error index: mongodb-sentiment.tweets.$_id_  dup key: { : ObjectId('55253ca980d0f50241e20c48') }]
  name: 'MongoError',
  code: 11000,
  err: 'E11000 duplicate key error index: mongodb-sentiment.tweets.$_id_  dup key: { : ObjectId(\'55253ca980d0f50241e20c48\') }' }
Document could NOT be inserted.
>{ [MongoError: E11000 duplicate key error index: mongodb-sentiment.tweets.$_id_  dup key: { : ObjectId('55253ca980d0f50241e20c48') }]
  name: 'MongoError',
  code: 11000,
  err: 'E11000 duplicate key error index: mongodb-sentiment.tweets.$_id_  dup key: { : ObjectId(\'55253ca980d0f50241e20c48\') }' }

- So, question 1 is not that relevant.
- For question 2, I guess that I need to deal with the http server itself to avoid the multiple calls, right? If you could provide any reference you's happen to know, I'd deeply appreciate it.
- For question 3, I found these references: http://stackoverflow.com/questions/24430220/e11000-duplicate-key-error-index-in-mongodb-mongoose and http://stackoverflow.com/questions/13454178/mongoerror-erre11000-duplicate-key-error which I think they'll help to solve the problem. So, correct me please if I'm wrong, this key handling has nothing to do with the driver but with the way mongo itself works, right?

**Comment by prabhu** [comment]
2. Print the request url
3. There is an index on the id field defined in your mongodb. Read about indexes

**Comment by saintedlama** [comment]
Database connections are opened lazy, this means that a connection is opened when the first db operation is issued. Unique key index problems are a feature of mongo db. Closing issue
