### ISSUE TITLE
Mongojs don't support upsert?

### ISSUE THREAD

**Issue by programus** [mafintosh/mongojs#19]
In [this link](http://www.mongodb.org/display/DOCS/Updating#Updating-UpsertswithModifiers), mongodb said it support `upsert` by an operation. 
I tried it in mongodb shell and it works fine. 

But when I try the same update function in mongojs, it failed to insert the document if does not exist. 

Here is the experiment:

In mongodb shell

```
> db.tc.find()
> db.tc.update({v:111},{'$push':{m:'a'}},true)
> db.tc.find()
{ "_id" : ObjectId("4fc58624f2e9e463dc04b1ad"), "m" : [ "a" ], "v" : 111 }
> db.tc.update({v:111},{'$push':{m:'b'}},true)
> db.tc.find()
{ "_id" : ObjectId("4fc58624f2e9e463dc04b1ad"), "m" : [ "a", "b" ], "v" : 111 }
>
```

Use mongojs in node.js interactive

```
> mongojs = require('mongojs')
{ ObjectId: [Function],
  connect: [Function] }
> db = mongojs.connect('test')
....(lots of output)
> tc = db.collection('tc')
> callback = function(err, docs) {
... console.log(JSON.stringify(docs));
... }
[Function]
> tc.remove();
undefined
> tc.find({}, callback);
{ _oncursor: { get: [Function], put: [Function] } }
> []
> tc.update({v:111},{'$push':{m:'a'}}, true);
undefined
> tc.find({}, callback);
{ _oncursor: { get: [Function], put: [Function] } }
> []
>
```

the `update(query, new_data, true)` does not work. 

Is there any solution?

**Comment by chovy** [comment]
Is there anyway to get the updated doc passed back in the callback of an upsert?

All I see is (err) being passed back.
