### ISSUE TITLE
How to do bulk "save" (update or create)?

### ISSUE THREAD

**Issue by bendulum** [mafintosh/mongojs#190]
I'm trying to do bulk update or create. In __mongodb__ `save` does update or create, if the document was not found.

My code looks something like this:
```
var bulk = this.table.initializeOrderedBulkOp();
_.each(this.imported.files, function(file) {
    bulk.find({filePath: file.filePath}).save({$set: file});
});
bulk.execute(_.bind(this.onUpdateDB, this));
```
Unfortunately __mongojs__ does not support `save` for bulk operations.
How would i achieve such a behaviour?
I want to do this in bulk, so I have a callback when all rows have been updated or created.

**Comment by kmiyashiro** [comment]
try upsert.

```js
bulk.find({
  filePath: file.filePath
}).upsert().update({
  $set: file,
});
```
