### ISSUE TITLE
Mongo 3.0 Support?

### ISSUE THREAD

**Issue by tejasmanohar** [mafintosh/mongojs#191]
Is there Mongo 3.0 Support? What about 2.0?

**Comment by kmiyashiro** [comment]
appears to work fine with mongo 3 and 2.

**Comment by saintedlama** [comment]
Works fine with mongodb 3, used the driver for mongodb 2 as well.

Tests run against version 3 and 2 https://travis-ci.org/mafintosh/mongojs and are working (beside a tailed cursor problem)
