### ISSUE TITLE
--harmony support for node v0.12.x

### ISSUE THREAD

**Issue by kmiyashiro** [mafintosh/mongojs#192]
I recently tried switching to node v0.12.2, but it seems that collections are no longer auto populating using proxies if I try to access them. Have you tested this?

**Comment by lope** [comment]
Also having trouble

**Comment by saintedlama** [comment]
The proxy feature is not enabled when running node --harmony

See output of `node --v8-options` 

```
  --harmony (enable all harmony features (except proxies))
        type: bool  default: false
```

**Comment by saintedlama** [comment]
You can use `--harmony-proxies` flag to enable proxies
