### ISSUE TITLE
MODULE_NOT_FOUND. Error immediately on require('mongojs')

### ISSUE THREAD

**Issue by methuz** [mafintosh/mongojs#199]
```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

mongojs version 1.0.0

There is nothing else in my file except `require("mongojs")`

**Comment by sorribas** [comment]
If you don't need tailable cursor, you can use 1.0.1. But there was a problem with tailable cursors on that release. I'm working on a fix.

**Comment by saintedlama** [comment]
This is no bug in mongojs but an info message that the native bson module backing the mongodb-core driver could not be found. You could check if all build prerequisites are installed on your ubuntu box.

You should report this issue to the mongodb-core driver project. See also issue #206
