### ISSUE TITLE
db.on undefined

### ISSUE THREAD

**Issue by btknorr** [mafintosh/mongojs#201]
I am using the latest 1.0.1 - what happened to the events?

```
var mongojs = require('mongojs');
var db = mongojs('dev-db');
console.log(db.on);
// outputs --> undefined
```

**Comment by petergdoyle** [comment]
I am seeing the same thing. i thought it was related to changing up to mongo 3. same thing with mongo  2.6.10 

but i am also seeing something worse when streaming on a tailable cursor

here is the code :  https://raw.githubusercontent.com/petergdoyle/estreaming/master/node/mongo_connect/streaming_client_mongojs.js 

here is the error: MongoError: No more documents in tailed cursor
    at Function.MongoError.create (/home/vagrant/estreaming/node/mongo_connect/node_modules/mongojs/node_modules/mongodb-core/lib/error.js:31:11)
    at nextFunction (/home/vagrant/estreaming/node/mongo_connect/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:579:50)
    at /home/vagrant/estreaming/node/mongo_connect/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:538:7
    at queryCallback (/home/vagrant/estreaming/node/mongo_connect/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:215:5)
    at Callbacks.emit (/home/vagrant/estreaming/node/mongo_connect/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:94:3)
    at null.messageHandler (/home/vagrant/estreaming/node/mongo_connect/node_modules/mongojs/node_modules/mongodb-core/lib/topologies/server.js:235:23)
    at Socket.<anonymous> (/home/vagrant/estreaming/node/mongo_connect/node_modules/mongojs/node_modules/mongodb-core/lib/connection/connection.js:259:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)

there is a fixed issues filed at mongo: https://jira.mongodb.org/browse/NODE-435

i am using mongojs-1.0.1

mongojs@1.0.1 node_modules/mongojs
├── thunky@0.1.0
├── each-series@0.2.0
├── to-mongodb-core@2.0.0
├── parse-mongo-url@1.1.0
├── xtend@4.0.0
├── once@1.3.2 (wrappy@1.0.1)
├── pump@1.0.0 (end-of-stream@1.1.0)
├── readable-stream@1.1.13 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── mongodb-core@1.1.33 (kerberos@0.0.12, bson@0.3.2)

**Comment by douwevdijk** [comment]
Sam here, getting message: Object ... has no method 'on'

**Comment by saintedlama** [comment]
Events got lost when migrating to mongodb-core driver. I'll take a look to fix this

**Comment by gianluca-venturini** [comment]
Same error also here (using version 1.0.2):
```
db.on('error',function(err) {
   ^
TypeError: Object mydb has no method 'on'
    at Object.<anonymous> (/Users/gianluca/Developer/test_mongojs/dist/server.js:27:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by saintedlama** [comment]
@sorribas @watson @mafintosh I pushed a preliminary draft implementation for bringing back events to WIP-fix-events branch https://github.com/mafintosh/mongojs/tree/WIP-fix-events

The problem when bringing back events is that the current `Database` instance does get an async function passed to retrieve the server instance. This is a problem when for example registering a `connect` event handler. What I did to circumvent the problem:

* Split `get-topology` into two modules: `get-topology` to return a `Server` or `ReplSet` instance and `connect` module to do the connection stuff (and auth)
* Pass the server (aka topology) returned from `get-topology` to mongojs `Database` constructor as additional argument (Currently named `server` but `eventemitter` could be the name to fit).
* Register event handlers on the passed server

Another variation for implementing this is that the mongojs `Database` instance would setup connect in it's constructor. This would reduce complexity in index.js file and could be a abstraction good fit.

What do you think @sorribas @watson @mafintosh ?

**Comment by watson** [comment]
@saintedlama glad you are looking into this. Just to get me up to speed here: In your branch, is the server object parsed to the `Database` constructor as the 2nd argument the same that is parsed to the callback of the `onserver` function?

**Comment by saintedlama** [comment]
Yes, it's the same. Need to do this because I could not access the server directly since it is wrapped in onserver function.

**Comment by watson** [comment]
@saintedlama Inside the `Database` object, how come you can't now just replace the calls to `_getServer` with with just accessing the new `_server` property?

**Comment by saintedlama** [comment]
The reason not to do this is that the database object may not be connected yet so `Database` always uses the `_getServer` async function to get a connected server object. For event registration we may not use the async `_getServer` because we would swallow `connect` events.

**Comment by watson** [comment]
Ah ok, I see... maybe the name `onserver` is a little misleading now that we also have a `server`

**Comment by saintedlama** [comment]
Second try in https://github.com/mafintosh/mongojs/tree/WIP-fix-events

This time a much cleaner approach pulling out a connect module that is reponsible for connecting db instances. Quite a lot of logic was moved to the Database module but does not hurt readability IMHO.

Tests added with prefix `test-events-`

What do you think @sorribas @watson @mafintosh? Shall I merge?

**Comment by saintedlama** [comment]
Fixed in master
