### ISSUE TITLE
I have got this bug

### ISSUE THREAD

**Issue by yoslabs** [mafintosh/mongojs#206]
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

ubuntu 14.04, found nothing on the web to solve this issue

**Comment by saintedlama** [comment]
This is no bug in mongojs but an info message that the native bson module backing the mongodb-native driver could not be found. You could check if all build prerequisites are installed on your ubuntu box.

You should report this issue to the mongodb-native driver project.

**Comment by saintedlama** [comment]
And could you give this issue a title that is more descriptive?

**Comment by yoslabs** [comment]
That is what I see on my console, thanks, I will report the problem

**Comment by saintedlama** [comment]
Will close the issue since it's no bug related to mongojs
