### ISSUE TITLE
Add upsert option for Bulk.find.update() and Bulk.find.updateOne() commands

### ISSUE THREAD

**Issue by Avengis** [mafintosh/mongojs#211]
With the following sentence I am unable to insert new documents if no one matches the search criteria:
```javascript
bulk.find(criteria).updateOne(updatedDoc);
```

Looking at the source I found the following statement at the file lib/bulk.js:57
```javascript
self._currCmd.updates.push({q: query, u: updObj, multi: multi, upsert: false});
```

It would be great to be able to set the upsert option to true. Something like the following:
```javascript
bulk.find(criteria).upsert().updateOne(updatedDoc);
```

Thanks

**Comment by saintedlama** [comment]
Fixed by #213
