### ISSUE TITLE
RFC: Should we use the `standard` code-style linter from feross?

### ISSUE THREAD

**Issue by watson** [mafintosh/mongojs#214]
Hi guys

I would like to convert mongojs to support [standard](https://github.com/feross/standard). I know this can quickly turn into a bikeshedding debate so let me just open by saying I personally don't care about what coding style we use - as long as we use one and preferably back it up by a linter.

The reason why I propose this is because:

- It will help contributors who create pull requests to make better pull requests
- It will catch my own stupid errors like misspelling of variable names, forgetting to require a module, forgetting to remove an old variable that's no longer used etc.

If you guys say go, I'll do the refactor :)

**Comment by saintedlama** [comment]
:+1:

**Comment by mafintosh** [comment]
:+1:

**Comment by mafintosh** [comment]
fixed in master
