### ISSUE TITLE
Add back connect function

### ISSUE THREAD

**Issue by saintedlama** [mafintosh/mongojs#216]
Currently we get quite some issues where people used mongojs.connect which is gone in 1.0.x versions. We could easily bring this function back. Question is: should we?

What do you think @mafintosh @watson @sorribas

**Comment by mafintosh** [comment]
:-1: thats why we bump the major version. We could at notice to the README though

**Comment by saintedlama** [comment]
:+1: for your :-1: will add a breaking changes section

**Comment by saintedlama** [comment]
Added "upgrading from 0.0.x to 1.0.x" section: https://github.com/mafintosh/mongojs/commit/e1157b04628d83f41b3e2ca3710c2cdec89a7dd8#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by watson** [comment]
Yeah, people should just learn to use the new API.

In extreme cases I've previously had success with writing an upgrade guide and linking to it from the readme when refactoring/breaking an API:

Case of point from the [opbeat-node](https://github.com/opbeat/opbeat-node) README.md:
> **Important:** If you've been using version 0.3.x or earlier, please read our [upgrade guide](https://github.com/opbeat/opbeat-node/wiki/Upgrade-to-version-1.0).
