### ISSUE TITLE
Using `count` on a collection with a 'dot' in the name(i.e `admin.users` returns a count of zero consistently

### ISSUE THREAD

**Issue by Sativaware** [mafintosh/mongojs#217]
Using version `1.0.2` of mongojs and performing a count on a collection with a 'dot' in the name(i.e `admin.users`) seems to produce a count of zero(0) even if collection contains documents.

The following sample code uses `count` to count the number of documents in two collections - one with a single name `smslog` and one which contains a dot in the name `admin.users`:

``` javascript
const mongojs = require('mongojs')
const db = mongojs('testing')

db.collection('smslog').count({}, function(err, res){
  console.log('smslog: ' + res)
})

db.collection('admin.users').count({}, function(err, res){
  console.log('admin.users: ' + res)
})
```
```
smslog: 1330
admin.users: 0
```

**Even if the `admin.users` collection contains documents a count of zero is always returned**. For collections using a single name(without a dot) the count is correct.

If the `admin.users` collection is renamed using an underscore instead of a dot(i.e `admin_users`) `db.collection('admin_users').count` returns the correct counting, **indicating that including a dot in collection names seems to be the cause**.

I've tracked down the potential problem with `count` to [`mongojs/lib/cursor.js` line 129](https://github.com/mafintosh/mongojs/blob/master/lib/cursor.js#L129) where the `colname` variable is set using `this._opts.fullCollectionName.split('.')[1]` - splitting the full collection name and accessing the `1` element discards other parts of the name and ends up querying using an incorrect collection name(and resulting in a count of zero).

The [following gist](https://gist.github.com/Sativaware/0f22f7532abfe0e3ca56/revisions)(see first diff) shows a potential fix for `count` - which replaces the db part of the full collection name string as opposed to splitting it and using an index.

Please could confirm this problem - version [`0.18.2`](https://github.com/mafintosh/mongojs/tree/v0.18.2) doesn't seem to have this problem.

Many thanks.

**Comment by saintedlama** [comment]
Could you send a test as pull request to reproduce this problem?

**Comment by naartjie** [comment]
awesome, thanks @saintedlama. Just tried it this side, and it's working.

Sorry for not submitting a test case, I tried but I didn't know enough about mongojs / tape in order to get it working.

**Comment by naartjie** [comment]
@saintedlama thanks for showing me the way now, I have modified your test case and added one more use-case in #277
