### ISSUE TITLE
Does mongojs support SSL/TLS connections?

### ISSUE THREAD

**Issue by Stellaverse** [mafintosh/mongojs#221]
Hi there,

First, thanks for the great software.

Does mongojs support ssl connections with verified certificates? I see using the native drive that the connection would look like so: http://mongodb.github.io/node-mongodb-native/2.0/tutorials/enterprise_features/

But I don't see any ability to declare options when connecting using `mongojs`, which are needed to pass through `sslValidate` and `sslCA` options.

**Comment by saintedlama** [comment]
Currently no

**Comment by saintedlama** [comment]
Master branch now supports SSL connections :dancers: 

```javascript
var db = mongojs('connectionString', ['somethings'], {
  ssl: true,
  cert: fs.readFileSync('/pathto/cert.crt'),
  key: fs.readFileSync('/pathto/cert.key'),
  rejectUnauthorized: false // self-signed certificate
})
```

**Comment by Stellaverse** [comment]
Excellent! Thanks for the quick work Saintedlama!

A follow-up question though. I've recently spun up a new SSL/TLS deployment using Compose.io (they call it a MongoDB+ deployment), and it will *only* accept SSL connections.

So using mongojs, I just added `?ssl=true` to the end of my connection string, and it worked.

I tried removing the `?ssl=true` option from my connection string, and I got a connection error.

I didn't provide any options for the cert or key.

So it seems as though it actually *was* already working, although it seems like it shouldn't have.

Any idea why this is?

**Comment by matthiasdg** [comment]
@Stellaverse sure your server configuration requires certificate validation? See http://docs.mongodb.org/manual/tutorial/configure-ssl/
IRRC anyone can connect if only PEM (instead of PEM + CA) is present in server config.

**Comment by Stellaverse** [comment]
I will go do my homework. Thanks @matthiasdg!

**Comment by Stellaverse** [comment]
Okay. So I've update `mongojs 0.18.0` to `mongojs 1.3.0` and now I can't connect. I can't figure out why for the life of me.

The connection code I'm using is as such:
```
var database = 'myDatabase';
var collection = 'myCollection';

var cs = 'mongodb://myMongoUser:myMogoPass@mongo-1.myapp.com:12345,mongo-2.myapp.com:54321/';

var connection = mongojs(cs + database, [collection], {
	ssl : true,
	authMechanism : 'ScramSHA1',
	//cert : fs.readFileSync('/Users/Me/.ssh/Database-Key.pem'),
	key : fs.readFileSync('/Users/Me/.ssh/Database-Key.pem'),
	rejectUnauthorized : false
});
```

In the above the `Database-Key.pem` file is the only file provided to me by my vendor. I believe this is because they don't yet support server verification.

Anyhow, the error I keep getting is as follows:
`{ [MongoError: no valid seed servers in list] name: 'MongoError', message: 'no valid seed servers in list' }`

And I've tried using my `Database-Key.pem` file as the value for cert as well. And for both of them as well.

Any idea how to debug this?
