### ISSUE TITLE
Allow access to the mongodb instance created

### ISSUE THREAD

**Issue by josevillacreses** [mafintosh/mongojs#223]
First of all, thanks for giving away this amazing project. The mental mapping between mongodb documentation and using this api is closed to none.

There is this closed issue #14  referring to the need of accessing the database instance in order to use it with connect-mongo. 

I'm in the very same need, and can't find the "client" property (referred in the issue 14) or anything similar.

Would you be so kind to guide me on how to get the database instance?

I'm using mongojs version 0.18.2.

Thanks for your help.

**Comment by saintedlama** [comment]
Instead of getting the mongodb connection from mongojs another approach can work for you: You can pass a mongodb instance to mongojs. This monodb instance can be used in connect-mongo as well.

**Comment by saintedlama** [comment]
Any update?
