### ISSUE TITLE
"Auth Failed" error since updating

### ISSUE THREAD

**Issue by BradDodi** [mafintosh/mongojs#225]
Hey,

Since updating to version 1.0.2 (though 1.0.0 most likely introduced my issue) I'm now receiving "Auth Failed" errors when executing a command. This is the full error:

    { [MongoError: auth failed]
    name: 'MongoError',
    message: 'auth failed',
    ok: 0,
    errmsg: 'auth failed',
    code: 18 }

I'm using `mongojs("mongodb://admin:password@IP_ADDRESS/bot")` to connect instead of the `connect()` function, which is now unsupported. Does the update to mongojs require the latest version of Mongodb?

EDIT: Updated Mongodb to the latest version and still receiving "auth failed" errors. Username and password is confirmed to be correct via command line and MongoChef.

EDIT 2: Downgrading to 0.18.2 has resolved it and I can connect again, so it does appear to be an issue since 1.0.0.

**Comment by saintedlama** [comment]
We just released version 1.2.0 if you want to give that version a try. It changes authentication and authentication mechanisms used in mongojs. What version of mongodb do you use? Could you post some code piece to demo your issue? What authentication mechanism do you use for authenticating against mongodb?

**Comment by BradDodi** [comment]
Hi saintedlama,

Thanks for the reply! I've just tried version 1.2.0 but unfortunately it's still resulting in an "auth failed" error when performing any command on a collection. It seems no matter how simple the code is it still results in this error, though here's an example:

    var util = require('util');
    var fs = require('fs');
    
    var mongojs = require("mongojs");
    
    var databaseUrl = "mongodb://admin:password@IP_ADDRESS/bot";
    var db = mongojs(databaseUrl);
    
    function testing() {
    	db.collection("#channel.users").find({ username: "brad_dodi" }, function(err, results) {
    		if (err) console.log(err);
    		else if (results.length > 0) console.log(results[0]);
    	});
    }
    testing();

And the resulting error:

    { [MongoError: auth failed]
    name: 'MongoError',
    message: 'auth failed',
    ok: 0,
    errmsg: 'auth failed',
    code: 18 }

I'm using the latest version of Mongodb (version 3.0.4) and Mongojs (version 1.2.0). I should also point out that connecting locally instead of using a remote IP address also doesn't make any difference and still causes the error. Downgrading to version 0.18.2 of Mongojs resolved this issue.

Thanks for the help!

**Comment by saintedlama** [comment]
I guess I resolved your problem. MongoDB 3.0 changed the default auth mechanism from MongoCR to SCRAM-SHA-1. You can specify (thanks to a pull request) this auth mechanism when connecting to mongodb:

```javascript
var db = mongojs('mongodb://admin:password@IP_ADDRESS/bot', [], { authMechanism : 'ScramSHA1' });
```
Works on my machine (MongoDB 3.0.4)

**Comment by BradDodi** [comment]
Aha! That has indeed resolved it.

Thanks again for your help.

**Comment by albe-rosado** [comment]
another solution , even easier could be upgrade Mongo DB to the last version, i had the same issue and that fix it ....
