### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by matteocontrini** [mafintosh/mongojs#226]
Hi @mafintosh,
can you publish an update to npm with the commits of the last month?

Thanks.

**Comment by mafintosh** [comment]
@saintedlama minor bump right? also did i remember to give you publish rights?

**Comment by matteocontrini** [comment]
`npm owner ls mongojs` shows he has access ;)

**Comment by mafintosh** [comment]
@matteocontrini can't run that from the mobile phone :) @saintedlama you wanna do this release then?

**Comment by saintedlama** [comment]
@mafintosh a bit nervous but will do the release :runner:  
Minor bump not a patch since we added functionality.

**Comment by saintedlama** [comment]
done

**Comment by matteocontrini** [comment]
Great, thank you

**Comment by mafintosh** [comment]
:tada:

**Comment by mafintosh** [comment]
@saintedlama in general you shouldn't worry about releasing. worst case we'll just patch update a fix :)

**Comment by saintedlama** [comment]
@mafintosh I always worry about releasing :baby_chick:
