### ISSUE TITLE
SCRAM-SHA-1 authMechanism not supported

### ISSUE THREAD

**Issue by Russ93** [mafintosh/mongojs#233]
The Usage
```javascript
// connect using SCRAM-SHA-1 mechanism
var db = mongojs('username:password@example.com/mydb', ['mycollection'], {authMechanism: 'ScramSHA1'})
```

Tried this and got
```javascript
mongojs(
	'mongodb://user:password@db.goportlight.com/mydb',
	[ **collections** ],
	{'authMechanism': 'ScramSHA1'}
)

// returned
{ [MongoError: auth failed] name: 'MongoError', ok: 0, errmsg: 'auth failed', code: 18 }
```

Then tried this and got
```javascript
mongojs(
	'mongodb://user:password@db.goportlight.com/mydb?authMechanism=SCRAM-SHA-1',
	[ **collections** ],
	{'authMechanism': 'ScramSHA1'}
)

Error: only GSSAPI, PLAIN, MONGODB-X509 or MONGODB-CR is supported by authMechanism
```

**Comment by saintedlama** [comment]
Seems that you try to connect to a mongodb server version < 3 which does not support scram sha 1. Just remove the authMechanism option to authenticate using mongocr which is the default prior version 3

**Comment by Russ93** [comment]
I am at Mongo version 3.0.4

MongoDB shell version: 3.0.4

db version v3.0.4
git version: 0481c958daeb2969800511e7475dc66986fa9ed5
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014

and it works when I connect with mongochef

**Comment by Russ93** [comment]
I ran this in the shell to check
```shell
> db.auth( {
	user: "user",
	pwd: "*****",
	mechanism: "SCRAM-SHA-1",
} )
> 1
```

**Comment by saintedlama** [comment]
The error is a bit odd since the error message above says:

    Error: only GSSAPI, PLAIN, MONGODB-X509 or MONGODB-CR is supported by authMechanism

So `ScramSHA1` is not in the list :smile: 

Could you try to remove the `authMechanism=SCRAM-SHA-1` part from the connection url.

**Comment by Russ93** [comment]
I tried is an every command returns this error
```javascript
mongojs(
	'mongodb://user:password@db.goportlight.com/mydb,
	[ **collections** ],
	{'authMechanism': 'ScramSHA1'}
)

// returned
{ [MongoError: auth failed] name: 'MongoError', ok: 0, errmsg: 'auth failed', code: 18 }
```

**Comment by lvmy86** [comment]
me too, use node-mongodb-native is ok.

**Comment by jmengelle** [comment]
I successfully connect to a mongo 3.x, with both url parameter, and option. 

Like : 

var mongojs = require('mongojs')
var url = 'mongodb://admin:password@host/db?authMechanism=SCRAM-SHA-1';
var db = mongojs(url,[],{authMechanism: 'ScramSHA1'});


But mongojs should parse the url to automatically add the option...and the option does not even have the same name ('SCRAM-SHA-1' vs  'ScramSHA1') ! Really...
