### ISSUE TITLE
No duplicate key error

### ISSUE THREAD

**Issue by ChicagoDave** [mafintosh/mongojs#235]
When inserting a document with a duplicate property, mongojs should be filling in the err object. It does not...just returns a null object.

This is a bug.

**Comment by dr-dr** [comment]
mongojs has been changed to use mongodb-core, the error checking on the documents[0] collection from the response in the core never led to the creation of the mongo error.. so mongodb-core said ok, so mongojs said ok.. 

raised an issue here..
https://github.com/christkv/mongodb-core/issues/41

**Comment by AMKohn** [comment]
I just created a pull that should fix this, please try it and let me know!
