### ISSUE TITLE
ensureIndex throws "no such cmd: createIndexes"

### ISSUE THREAD

**Issue by woistjadefox** [mafintosh/mongojs#248]
Hey guys, I'm running a node.js 10.12 instance, connected to a mongodb 2.4 on an openshift server and I can't ensure indexes with mongojs. I always get the error in the title. 
![image](https://cloud.githubusercontent.com/assets/9056181/9823118/a7a4e268-58c4-11e5-928e-5ab14e875802.png)

Any ideas?

**Comment by saintedlama** [comment]
Should be fixed in version 2.0 (released just some seconds ago)

**Comment by saintedlama** [comment]
Any update on this issue?
