### ISSUE TITLE
Feature request: Unable to pass options to .aggregate()

### ISSUE THREAD

**Issue by bounceg** [mafintosh/mongojs#249]
Using MongoJS 1.3.0 I am unable to pass options to the .aggregate() function as per the [docs](http://docs.mongodb.org/manual/reference/command/aggregate/), instead of just the pipeline array.

Specifically, I'm trying to pass allowDiskUse: true.

Example:

```
cursor = db
.collection('myCollection')
.aggregate({
   pipeline: [{}, {}, ... ]
   allowDiskUse: true
});
```

**Comment by mrpelle** [comment]
+1 on this. I need to pass `readPreference: 'secondaryPreferred'`

**Comment by thenovelnomad** [comment]
+1

**Comment by sokardys** [comment]
+1

**Comment by carlos-lopez** [comment]
+1
