### ISSUE TITLE
Use Request Body to Update Entire Document

### ISSUE THREAD

**Issue by ewcbyrd** [mafintosh/mongojs#260]
Using AngularJS, I am trying to update an entire document by passing in the document contents in the request body the use the findAndModify method to replace the existing document. It does not work.

CONTROLLER:
```js
$scope.updateChecklist = function() {
		$http.put('/checklist/' + $scope.checklist._id, $scope.checklist).success(function(response) {
			$scope.checklist = response;
		});
};
```

SERVER:
```js
app.put('/checklist/:id' , function(req, res) {
	
	var id = req.params.id;
	
	db.checklist.findAndModify({query: {_id: mongojs.ObjectId(id)}, 
		update: {$set:req.body}, 
		new: true}, function(err, doc) {
			console.log(doc);
			res.json(doc);
		}); 
});
```

**Comment by watson** [comment]
@ewcbyrd try and log the returned `err` argument in the `findAndModify` callback to see if you get an error

**Comment by ewcbyrd** [comment]
@watson, thank you for the tip. The error message that was returned led me right to the problem. The scope object that was passing in contain the _id that mongodb assigned to the record. In doing so I was attempting to overwrite the key, which was throwing an error. I updated the controller as follows top fix the problem:

$scope.updateChecklist = function() {
		var id = $scope.checklist._id;
		delete $scope.checklist._id;
		$http.put('/checklist/' + id, $scope.checklist).success(function(response) {
			console.log(response);
			$scope.checklist = response;
			$scope.update='true';
		}); 
};

**Comment by watson** [comment]
@ewcbyrd glad I could help :smiley:
