### ISSUE TITLE
[question] How/why do you defer connection?

### ISSUE THREAD

**Issue by wearhere** [mafintosh/mongojs#261]
The [official MongoDB driver](https://github.com/mongodb/node-mongodb-native) only vends the `db` reference after connection:

```js
MongoClient.connect(url, function(err, db) {
  insertDocuments(db, function() {
    updateDocument(db, function() {
      db.close();
    });
  });
});
```

whereas with `mongojs` you are able to do

```js
var db = mongojs(url);
db.collection('test').insert(…);
```

Do you lazily connect to the database, or connect synchronously? And once connected, do you then hold that connection open to implement connection pooling?

I prefer your syntax, am just confused why the official driver wouldn't do it this way—seems simpler.

**Comment by watson** [comment]
Yes we connect to the database on the first connection attempt using [thunky](https://github.com/mafintosh/mongojs/blob/5e04437306b07e18c2e40d295d9135d3f595b473/lib/database.js#L21-L23). Behind the scene we wrap [mongodb-core](https://github.com/christkv/mongodb-core) and either instantiate a [new Server](https://github.com/mafintosh/mongojs/blob/5e04437306b07e18c2e40d295d9135d3f595b473/lib/get-topology.js#L14) or [new ReplSet](https://github.com/mafintosh/mongojs/blob/5e04437306b07e18c2e40d295d9135d3f595b473/lib/get-topology.js#L20) depending on the connection type and reuse that.

**Comment by wearhere** [comment]
Neat! Thanks for the quick response & clever implementation.
