### ISSUE TITLE
Hangs up when mongo connection is down

### ISSUE THREAD

**Issue by alexbeletsky** [mafintosh/mongojs#266]
I have quite simple setup, as middleware for expressjs application,

```js
function createConnection(config) {
 var connection;

  const collections = [
    'users',
    'prospects',
    'leads',
    'opportunites',
    'connections',
    'campaigns',
    'personas',
    'sources'
  ];

  if (!connection) {
    connection = mongo(config.connection, collections);

    connection.on('error', (err) => {
      logger.fatal('mongo connection error', err);
    });

    connection.on('connect', () => {
      logger.success('connected to mongo');
    });
  }

  return (req, res, next) => {
    req.mongo = connection;
    next();
  };
}
```

I remember from previous versions, if constructor function called, but mongo instace was down, the exception was thrown (or null returned, so it was possible to check).

With version `"mongojs": "^1.4.1",` the constuctor returns intialized object and on a call to mongo, `findOne()` for instance, callback never called.

`error` and `connect` callbacks are never called.

**Comment by saintedlama** [comment]
Should be fixed in version 2.0 (released just some seconds ago)

**Comment by alexbeletsky** [comment]
Thx @saintedlama I'll try that tonigh and close the ticket if problem is solved.

**Comment by saintedlama** [comment]
Did it work as expected?

**Comment by alexbeletsky** [comment]
So, the current behaviour is: initialized object is returned, on call error handler is triggered, call doen't hang.

Works as expected.
