### ISSUE TITLE
cant create collection

### ISSUE THREAD

**Issue by angelo0000** [mafintosh/mongojs#267]
I am running mongo 3.0.7 and mongojs 0.18.2 (using this version since it still uses the native driver)

The following code fails with exception:

db.createCollection("somecollection" , function(err, res){
    console.log('woot');
});

TypeError: Cannot call method 'filter' of undefined
    at mongojs/node_modules/mongodb/lib/mongodb/db.js:469:49
    at mongojs/node_modules/mongodb/lib/mongodb/db.js:1183:7
    at mongojs/node_modules/mongodb/lib/mongodb/db.js:1916:9
    at mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:448:41

Is there a workaround for this?

**Comment by saintedlama** [comment]
Should be fixed in version 2.0 (released just some seconds ago)

**Comment by angelo0000** [comment]
This now throws different issues in other areas: Maximum call stack exceeded.

/express/node_modules/mongojs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:247
      throw err;
            ^
RangeError: Maximum call stack size exceeded

**Comment by saintedlama** [comment]
Could you post a bit of the code that leads to the RangeError? Seems releated to #270

**Comment by saintedlama** [comment]
Fixed by #270
