### ISSUE TITLE
Scope option is not passed to mapReduce

### ISSUE THREAD

**Issue by theres** [mafintosh/mongojs#271]
In mongo documentation there is 'scope' option in mapReduce. Now, this field is not filled when mapReduce is called. Also, when I tried call runCommand I've problem to pass throught scope (probably because of serialization). 

I found quite ugly workaround accessing to node-mongodb-native collection and run theirs implementation, but IMHO this should work this way in mongojs.

**Comment by saintedlama** [comment]
Fixed in git. We're using the mapReduce functionality offered by node-mongodb-native

**Comment by saintedlama** [comment]
And already released on npm as 2.2.0
