### ISSUE TITLE
Create Unique Compound Index

### ISSUE THREAD

**Issue by vertangelx** [mafintosh/mongojs#273]
How can compound index be created?

Tried `Fruits.createIndex(['name', 'color'], {'unique': true})` but did not work.

**Comment by saintedlama** [comment]
Just take a look at the mongodb docs https://docs.mongodb.org/v3.0/core/index-compound/

For your problem the solution should look somehow like this `Fruits.createIndex({ 'name' : 1, 'color': 1}, {'unique': true})`
