### ISSUE TITLE
I have too many of idle process, how to set max maxIdleTimeMS?

### ISSUE THREAD

**Issue by chaintan17** [mafintosh/mongojs#275]
When i run `db.currentOp(true)`, there are 800+ connections.
Almost, if not all, of them has `active : false`.
And when the connection is too much, it make mongodb unreachable and have timeout error.

I use ur drive with hapijs framework, please advise how to resolve this error
or set `maxIdleTimeMS` please.
Thank you.

**Comment by saintedlama** [comment]
IMHO the connection management in your application is broken. Mongojs uses mongodb-native which manages connections in a connection pool for you. You should *NOT* open a connection (in the default case 5 connections in a connection pool) for every request but have one (mongojs) db instance and let the instance manage your connections.

If that solution sounds awkward to you you can pass the option in the connection string URL. See the mongodb docs for more information https://docs.mongodb.org/v3.0/reference/connection-string/

**Comment by Globik** [comment]
Hm, I don't see any harmony Proxy object in your source code of mongojs. What does it mean?

**Comment by saintedlama** [comment]
@Globik it means everything. But what does the comment mean?

**Comment by Globik** [comment]
I can't run mongojs with proxy feature.  db.hucker.find() does not work. No matter if there is --harmony flag or not.

**Comment by saintedlama** [comment]
@Globik why not open an issue for this question?
