### ISSUE TITLE
Documentation changes and getting warning on installation

### ISSUE THREAD

**Issue by Kishanrajdev047** [mafintosh/mongojs#278]
Hi,

Would like to thank you for contributing a great module to work with mongodb. Few changes i want you to make in your documentation. Had to spend plenty of hours for debugging before it worked.

    // find everything
    var db = mongojs('test')
    var mycollection = db.collection('my_collection');

    // this doesn't work 
    /*db.mycollection.find(function (err, docs) {
        // docs is an array of all the documents in mycollection
    })*/

    //this works
    mycollection.find(function (err, docs) {
        console.log(err);
        console.log(docs);
    })

Also getting below warning on installation of mongojs or mongodb driver

    t/kerberos/lib/kerberosgss.o../lib/kerberosgss.c:509:13: warning: implicit declaration of function     'gss_acquire_cred_impersonate_name' is invalid in C99 [-Wimplicit-function-declaration] maj_stat =     gss_acquire_cred_impersonate_name(&min_stat,

what could be the issue?

Thanks.

**Comment by watson** [comment]
I think you can safely ignore the warning you are getting - it at least have nothing to do with how you perform a query when using mongojs.

There are two ways you can "load up" the collections you need access to:

Options A - supply collection names up front in an array:

```js
var db = require('mongojs')('mydb', ['mycollection'])
db.mycollection.find(...)
```

Options B - lazy load the collections using `db.collection()`:

```js
var db = require('mongojs')('mydb')
var mycollection = db.collection('mycollection')
mycollection.find(...)
```

Notice that we in option B go through the mycollection variable and NOT db. You can choose either pattern - whatever suits your problem best - but It seems that you are getting option A and B mixed up.

**Comment by Kishanrajdev047** [comment]
worked. Thanks. Closing the ticket.
