### ISSUE TITLE
How to get query's length ?

### ISSUE THREAD

**Issue by mdennyh** [mafintosh/mongojs#279]
In mongodb I can use: 
db.transaction.find().length()
As long as I can tell I can't use the length() function in mongojs

**Comment by watson** [comment]
@mdennyh if you are interested in the number of documents that matches your query consider using count instead if find: `db.collection.count(query)`

Does this answer your question?

**Comment by mdennyh** [comment]
Ah You're right, It answers my question, Thank you. I used to query all the document I have to count its length
