### ISSUE TITLE
Authentication against authSource doesn't work

### ISSUE THREAD

**Issue by dilignt** [mafintosh/mongojs#282]
I'm having problems connecting to a mongodb instance using a connection string that authenticates a user in the admin database for accessing all databases.  This seems to be related to [this issue](https://github.com/mafintosh/mongojs/issues/158) which I commented on but has been closed.

I'm unable to get the authentication to work on Windows 10 with MongoDB v3.2.0.  With the following web user I can show collections in the test database using the shell
```
$ mongo
MongoDB shell version: 3.2.0
connecting to: test
> use admin
switched to db admin
> db.auth('web', 'k1ll3r5')
1
> use test
switched to db test
> show collections
store
>
```
But when I try to do the equivalent using this code with mongojs with  the `authSource` option
```
var mongojs = require('mongojs');

var db = mongojs('web:k1ll3r5@localhost/test?authSource=admin');

db.getCollectionNames(function(err, names) {
    console.log(arguments);
});
```
it won't authenticate
```
{ '0':
   { [MongoError: auth failed]
     name: 'MongoError',
     message: 'auth failed',
     ok: 0,
     errmsg: 'auth failed',
     code: 18 } }
```
but using node-mongodb-native driver works as follows
```
var MongoClient = require('mongodb').MongoClient;

var db = MongoClient.connect('mongodb://web:k1ll3r5@localhost/test?authSource=admin', function (err, db) {

    db.collections(function(err, names) {
       console.log(arguments);
       db.close();
    });

});
```
which gives no error and the collections array
```
{ '0': null, '1': [ { s: [Object] } ] }
```
What is going wrong with mongojs?

many thanks in advance

**Comment by saintedlama** [comment]
What mongojs version are you using? Just tried it with mongojs `2.2.2` and I'm getting the same results with mongojs as with mongodb-native. I'm using mongodb 3.0.4.

**Comment by dilignt** [comment]
I've got mongojs version 1.4.1, which is what I get with ```npm install mongojs```.  I take it this is installing the wrong version?

**Comment by saintedlama** [comment]
Upgrade to version 2.x and it should work out of the box. We changed the backing driver from mongodb-core to mongodb-native that can deal with authSource out of the box.

**Comment by dilignt** [comment]
I've just done `npm install mongojs@2.2.2` and you're right, it does now work.  But why doesn't `npm install` install the latest version by default?

thanks for your help

**Comment by saintedlama** [comment]
I guess you're using a semver expression like `^1.4.1` for mongojs in your package.json which will install all 1.x.x versions but no 2.x.x versions.

My recommended tool for keeping up with new package releases is npm-check-updates (https://www.npmjs.com/package/npm-check-updates)

**Comment by dilignt** [comment]
Yes, you're right - I hadn't noticed that it was specified in a package.json.file

thanks again :)
