### ISSUE TITLE
Getting error while connecting to MongoDB through mongoJS

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [mafintosh/mongojs#283]
I am getting the following error while connecting to the MongoDB through mongoJS.

```
process.nextTick(function() { throw err; })
                                      ^
 Error: connect UNKNOWN 127.0.0.1:27017 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at connect (net.js:843:14)
    at net.js:939:9
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

I am running the my MongoDB using the command mongod --dbpath C:\new --journal.I am explaining my code below.

```
var mongo=require('mongojs');
var database='medilink';
var collections=['admin','supplier'];
var db=mongo("mongodb://127.0.0.1:27017/"+database, collections);
```
Let me to confirm you that i am using mongojs -v 2.2.2 and using 32 bit win-xp system.Please help me to resolve this error.

**Comment by mrvautin** [comment]
http://stackoverflow.com/questions/31228809/mongoerror-connect-unknown

**Comment by subhrajyotiw5rtc** [comment]
@mrvautin : The url provided by you is about mongodb  driver.Here i am using mongoJS.Is there compatibility error this is ?

**Comment by saintedlama** [comment]
Mongojs uses mongodb native under the hood so these issue applies to mongojs as well. You could stick to a pre 1.0.0 version to circumvent the issue
