### ISSUE TITLE
Error: connect is not a function

### ISSUE THREAD

**Issue by jhyland87** [mafintosh/mongojs#286]
I setup a database at MongoLab, and I can connect to it via the CLI using `mongo` just fine, so I know the credentials are just fine, but when I try to connect using `mongojs`, I get an error: 

> TypeError: require(...).connect is not a function

The script itself is about as basic as it gets, it's only got one line of JS:

```javascript
var db =
require('mongojs').connect('my_user:secret@ds047365.mongolab.com:47365/my_database')
```

Admittedly, this is my first attempt at working with MongoDB, but this is copied straight out of a few examples Ive found online. Am I doing something wrong?

Heres the full error/stacktrace
```
$ node connect.js
/Users/me/Documents/scripts/js/node/test/mongodb/test_connection/connect.js:3
var db = require('mongojs').connect('my_user:secret@ds047365.mongolab.com:47365/my_database');
                            ^

TypeError: require(...).connect is not a function
    at Object.<anonymous> (/Users/me/Documents/scripts/js/node/test/mongodb/test_connection/connect.js:3:29)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

**P.S.**: I had a hard time installing `mongodb` via npm, as it was throwing errors saying I didnt have kerberos installed, and kerberos was failing due to something related with xcode, (same error as in [this thread](http://stackoverflow.com/questions/33140089/failing-to-install-mongoose-npm/33140170#33140170)). Eventually I just installed mongodb via brew... Would mongodb being installed via brew instead of npm be the problem? I see mongodb is a dependency of mongojs..

**Comment by saintedlama** [comment]
mongojs does not expose a connect function anymore (since 1.x release). Simply use

var db =
require('mongojs')(URL)

To connect.

**Comment by jhyland87** [comment]
Ah! ok, that makes sense...

```javascript
var databaseUrl = "my_user:secret@ds047365.mongolab.com:47365/my_database";
var mongojs = require('mongojs')
var db = mongojs(databaseUrl);
var test = db.collection('test')

test.find(function (err, docs) {
    if(err)throw new Error(err)
    console.log('DOCS',docs)
})
```

Perfect, thank you!
