### ISSUE TITLE
mapReduce emit()function 

### ISSUE THREAD

**Issue by dpark1985** [mafintosh/mongojs#288]
Hello,

While I was working with db.collection.mapReduce to get the KEYs from database, I get an error that saying 
> ReferenceError: emit is not defined

from the official [mongodb doc mapreduce](https://docs.mongodb.org/manual/reference/command/mapReduce/#mapreduce-map-cmd), there is a function 
> emit(key,value)

to emit key and value pair.

Can anyone help me on this??
Thank you

Below is the snippet of the code
```
	var mapFunction = function(){
		for (var key in this){
			emit(key, null);
		}
	};

	var reduceFunction = function(key, value){
		return null;
	}

	var options = {
		out: "keys",
		query: null,
		sort: null,
		limit: null,
		keeptemp: false,
		finalize: null,
		scope: null,
		jsMode: false,
		verbose: false,
		bypassDocumentValidation: false
	};


	collection.mapReduce(mapFunction(), reduceFunction(), options, function (err, data){
		console.log(data);
	});
```

**Comment by saintedlama** [comment]
The functions map and reduce need to be passed as functions in the code above. Instead of 

```
collection.mapReduce(mapFunction(), reduceFunction(), options, function (err, data){
  console.log(data);
});
```

Use (note the missing parentheses after `mapFunction` and `reduceFunction`)

```
collection.mapReduce(mapFunction, reduceFunction, options, function (err, data){
  console.log(data);
});
```

**Comment by saintedlama** [comment]
@dpark1985 is it working for you?

**Comment by dpark1985** [comment]
@saintedlama yes. Thank you.
