### ISSUE TITLE
Getting native mongodb driver from mongojs

### ISSUE THREAD

**Issue by navinSing** [mafintosh/mongojs#291]
db.collection.insertMany (is returning null) is failing ..

insertMany is present in original driver : https://www.npmjs.com/package/mongodb#inserting-a-document

Hence looking for native mongoDb drive from mongojs

Want to keep most of the stuff on native drivers incase need to migrate.

**Comment by saintedlama** [comment]
You can use `insert` in mongojs to insert an array of docs into mongodb.

dB.collection.insert([docs]...
