### ISSUE TITLE
Cursor.sort() used together with forEach() limits results to the default page size (1000)

### ISSUE THREAD

**Issue by olegam** [mafintosh/mongojs#293]
When I chain a `.sort()` statement to my cursor I only get 1000 results even though the query matches much more documents.

This example
```
var cursor = db.documents.find({})
var objectsCount = 0
cursor.forEach(function (err, res) {
  if (!res) console.log('number of objects found:', objectsCount)
  objectsCount++
})
```
prints output:
```
number of objects found: 1003221
```

But this example where i added the `sort()`:
```
var cursor = db.documents.find({})
var objectsCount = 0
cursor.sort({date: 1}).forEach(function (err, res) {
  if (!res) console.log('number of objects found:', objectsCount)
  objectsCount++
})
```
prints:
```
number of objects found: 1000
```

Am I doing anything wrong here or is there some issue with the sort function?

**Comment by olegam** [comment]
I submitted a PR with a failing test case.

**Comment by olegam** [comment]
So.. Upgrading to the latest version of mongodb from homebrew fixed this. We can close.

**Comment by saintedlama** [comment]
You upgraded the mongodb server?From which version to which version? I remember that there is a bug in some older versions of mongodb with sorting and query result length but not in which version that was fixed...

**Comment by olegam** [comment]
The old one with the error was 2.4.1
