### ISSUE TITLE
Update mongodb module to 2.0.55

### ISSUE THREAD

**Issue by spiritinlife** [mafintosh/mongojs#296]
MongoDb 2.0.55 patch https://github.com/mongodb/node-mongodb-native/blob/2.0/HISTORY.md#2053-12-23-2015

I have been talking with mongolab support about some increasing connections i have seen in my production database.
They told me that this patch https://github.com/mongodb/node-mongodb-native/blob/2.0/HISTORY.md#2053-12-23-2015 adds significant connection management improvements.
I am going to test in my local environment with the mongodb version set to 2.0.55 and report back.
I would like to hear your input and if you tried this version of mongodb or plan to support it .

Thanks,
George

**Comment by saintedlama** [comment]
Mongojs depends on mongodb semver version ^2.0.45 so the most current mongodb version < 3 is installed when installing mongojs. No need to upgrade :+1:

**Comment by spiritinlife** [comment]
Exactly ! 
I rushed to report because of the problems i was seeing :/
Sorry for opening the issue and thanks for the reply!
