### ISSUE TITLE
Proxy error when using with Electron

### ISSUE THREAD

**Issue by artturimatias** [mafintosh/mongojs#302]
I'm using mongojs with Electron in order to build desktop app. However, Mongojs throws following error: 
`TypeError: Proxy.create is not a function`
It seems that electron provides Proxy object but there is no Proxy.create function. If I change this in index.js (line 6)
`if (typeof Proxy !== 'undefined') {`
to this:
`if (typeof Proxy.create !== 'undefined') {`
everything works as expected.

This is not a proper fix but it makes mongojs to work with Electron.

**Comment by sorribas** [comment]
What version of mongojs? This issue should be fixed in the latest release?

**Comment by artturimatias** [comment]
Sorry for noise. Updating to latest fixed the issue.
