### ISSUE TITLE
Synchronious mongojs

### ISSUE THREAD

**Issue by thatisuday** [mafintosh/mongojs#307]
Hi I am using mongodb version 3.0.7 and v2.4.0 of mongojs.

```
var pushNested = function(doc, index, orgDocs){
		orgDocs[index].sub = []; // Sub categories container
		
		if(parseInt(orgDocs[index].level) <= levels){
			db.product_categories.find({
				$and : [
					{
						cat_id : new RegExp('^' + orgDocs[index].cat_id, 'gi')
					},
					{
						level : parseInt(orgDocs[index].level) + 1
					}
				]
			}).toArray(
				function(err, subDocs){
					if(subDocs){
						_.each(subDocs, function(subDoc, subIndex, orgSubDocs){
							pushNested(subDoc, subIndex, orgSubDocs);
							orgDocs[index].sub.push(subDoc);
						});
					}
				}
			);
		}
	}
```

I have a recursive function as above. The problem here is that mongojs is **async** and that's why `pushNested` get called even when the response from previous request is not resolve.

**Hence, It's my request to create some functionality like  `db.col.findSync` to address some problems where synchronicity is must.**

**Comment by mafintosh** [comment]
there is no sync tcp api in node so unfortunately that isn't possible. adding a callback to your function will solve it as well no?

**Comment by thatisuday** [comment]
Well in this particular example, unfortunately that's not possible. I was
unaware of node doesn't provide sync TCP api. I guess I have to try
something else, may be $q library

**Comment by mafintosh** [comment]
since node has this limitation i'm not sure any other library will help you unless it is doing some particular crazy core hacks which i wouldn't not recomment. just fyi. hope you figure it out :)

**Comment by thatisuday** [comment]
Promises works. But this is not not a safe solution.

```
var solvers = 0, resolved = 0;
var pushNested = function(doc, index, orgDocs){
		orgDocs[index].sub = []; // Sub categories container
		
		if(parseInt(orgDocs[index].level) <= levels){
			solvers ++;
			db.product_categories.find({
				$and : [
					{
						cat_id : new RegExp('^' + orgDocs[index].cat_id, 'gi')
					},
					{
						level : parseInt(orgDocs[index].level) + 1
					}
				]
			}).toArray(
				function(err, subDocs){
					if(subDocs){
						_.each(subDocs, function(subDoc, subIndex, orgSubDocs){
							pushNested(subDoc, subIndex, orgSubDocs);
							orgDocs[index].sub.push(subDoc);
						});
					}
					
					if(solvers == ++resolved){
						deferred.resolve();
					}
				}
			);
		}
	}
```
