### ISSUE TITLE
Issues passing Mongojs a native MongoDB instance

### ISSUE THREAD

**Issue by mrvautin** [mafintosh/mongojs#308]
There seems to be an issue when passing a native MongoDB connection/object to Mongojs. It seems to be failing because the value of `connString.options.url` is undefined and when passed to `parse-mongo-url` is fails on line 11 due to the value being undefined. 

I've tracked it down to this section in `/lib/database.js` on line 43: 

`this._dbname = parse(connString.options.url).dbName`

In code:

``` javascript
} else { // try mongodb-native
    this._dbname = parse(connString.options.url).dbName

    this._getConnection = thunky(function (cb) {
      cb(null, connString)
    })
  }
```

When looking at the `connString` object it doesn't seem to have the connection URL which is expected by `mongojs`. 

Any ideas?

I'm running:

```
"mongodb": "^2.1.4"
"mongojs": "^2.2.2"
```

Node: v5.4.1

**Comment by saintedlama** [comment]
Fixed by #c5e170d758a8c16cc3d3c03a8a428c2ff254e92b
