### ISSUE TITLE
Correction in your documentation 

### ISSUE THREAD

**Issue by rajegit** [mafintosh/mongojs#312]
For 
/```
/ connect now, and worry about collections later
var db = mongojs('mydb')
var mycollection = db.collection('mycollection')

```
read
```

// connect now, and worry about collections later
var db = mongojs('mydb')
var mycollection = db.collection('mycollection')

```
Hereafter use mycollection instead of db.mycollection , ie for following examples would be 
```

// find everything
mycollection.find(function (err, docs) {
    // docs is an array of all the documents in mycollection
})

```
```

**Comment by saintedlama** [comment]
This proposed change does not improve readability IMHO
