### ISSUE TITLE
Mongo query hang

### ISSUE THREAD

**Issue by alanshaw** [mafintosh/mongojs#317]
I've run into a problem when using mongojs 2.4 and the latest mongodb driver (v2.2.1 - which it depends on) and I'm raising it here so anyone else with the same problem can hopefully resolve quickly. I don't think this is mongojs's fault.

3 days ago v2.2.1 of mongodb driver was released and we noticed that after a period of inactivity our mongojs queries would hang. We have another project that was deployed using the same version of mongojs, but the mongodb driver that was installed (as a dependency) is version v2.1.21 - this project does not exhibit the same hanging behaviour.

Downgrading to v2.1.21 of the mongodb driver fixed our problem - no hangs when we leave the site alone for a while and come back.

We're using mongo server 3.2 btw.

Right now I'm speculating that this is a bug with the mongodb driver's connection pool which was [redesigned in v2.2](https://github.com/mongodb/node-mongodb-native/blob/2.2/docs/reference/content/upgrade-migration/index.md#whats-new-in-22).

**Comment by rahbari** [comment]
I had a similar problem with mongo core 2: https://github.com/christkv/mongodb-core/issues/120
Would you please tell me how to downgrade Mongodb driver without touching mongojs package?

**Comment by rahbari** [comment]
This is how to downgrade as a temporary fix:

```
npm uninstall mongodb
npm install mongodb@2.1.21
```

**Comment by saintedlama** [comment]
Should be fixed by an updated version of thunky
