### ISSUE TITLE
no primary found in replicaset

### ISSUE THREAD

**Issue by osher** [mafintosh/mongojs#319]
Hi.

We're using mongojs@2.3.0
Our production uses node v0.12.7, running on CentOS.

We're getting the `no primary found in replicaset` error  from mongo.

**BUT** 

I suspect the problem is in the inner dependency `mongodb@2.2.1`
The problem is not reproduced when I force the dependency `mongodb@2.1.21`
(done by 
1 - `rm -r node_modules/mongojs`
2 - `npm install mongodb@2.1.21 --save`, 
which yields:

```
mongodb@2.1.21 node_modules\mongodb
├── es6-promise@3.0.2
├── readable-stream@1.0.31 (string_decoder@0.10.31, isarray@0.0.1, inherits@2.0.1, core-util-is@1.0.2)
└── mongodb-core@1.3.21 (bson@0.4.23, require_optional@1.0.0)
```

  and then 
3 - `npm install`
which yields 

```
mongojs@2.3.0 node_modules\mongojs
├── thunky@0.1.0
├── each-series@1.0.0
├── to-mongodb-core@2.0.0
├── parse-mongo-url@1.1.1
├── xtend@4.0.1
├── once@1.3.3 (wrappy@1.0.2)
└── readable-stream@2.1.4 (buffer-shims@1.0.0, inherits@2.0.1, process-nextick-args@1.0.7, util-deprecate@1.0.2, string_decoder@0.10.31, isarray@1.0.0, core-util-is@1.0.2)
```

don't ask me how I got to that)

**SO:**

1) I thought you might want to know for yourselves
2) I can't find where to report bugs to them...
Can anybody tell me how to do that?

**Comment by VovaMukovozov** [comment]
i also encountered the same problem!

**Comment by dr-dimitru** [comment]
@mafintosh any news around this issue?

**Comment by KenanSulayman** [comment]
@dr-dimitru it's an upstream issue by mongodb directly.

**Comment by dr-dimitru** [comment]
@KenanSulayman any chance to get link to source code which causes this issue?

**Comment by saintedlama** [comment]
As upstream issue is fixed this issue is closed
