### ISSUE TITLE
[question] is it necessary to call `db.close` when you're done with the connection?

### ISSUE THREAD

**Issue by wearhere** [mafintosh/mongojs#323]
Hi, in my application I create secondary DB connections for some long-running operations (per the recommendation of http://mongodb.github.io/node-mongodb-native/2.0/reference/faq/#how-can-i-avoid-a-very-slow-operation-delaying-other-operations). Is it necessary to call [`close`](http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html#close) on them when done? i.e.

``` js
var db = mongojs(...);

db.collection('foo').update(..., function(err) {
  db.close();  // Is this necessary?
});
```

What happens if I don't call `close` and `db` just drops out of scope and gets garbage collected?

**Comment by mihai-iorga** [comment]
Uhm, I think `db` does not drop out and the connection stays alive. Your long-running process will hang until one of the endpoints gives up (you either call `db.close()` and close connection or mongo will close connection after).

**Comment by wearhere** [comment]
Ok thanks!
