### ISSUE TITLE
Mongojs and Promises

### ISSUE THREAD

**Issue by julianusti** [mafintosh/mongojs#324]
Do you have in plans to support Promise? If so, then when?

**Comment by sorribas** [comment]
Hello @julianusti. Promises are out of the scope of `mongojs`. You might want to check [promised-mongo](https://www.npmjs.com/package/promised-mongo), which is a `mongojs` based library with promise support.

**Comment by wearhere** [comment]
I don't suppose you'd reconsider this now that native async/await support has landed in Node 7? Many companies will begin using promises now (if they're not already) and that will only accelerate when Node 8 goes LTS in the fall.

**Comment by aPoCoMiLogin** [comment]
@sorribas the thing is that `mongodb` package has support for promises since 2.2.0 (Jul 8 2016).

**Comment by saintedlama** [comment]
You can checkout https://www.npmjs.com/package/mongoist 

it's a mongojs port with proxy support for collections, written with async/await in mind

**Comment by wearhere** [comment]
@saintedlama that looks terrific!! Thanks for making it. Really nice tests and docs—[this](https://github.com/saintedlama/mongoist#motivation) in particular is a great explanation of why mongojs and mongoist are easier to use than the official driver. Love that you added an [easy way to migrate](https://github.com/saintedlama/mongoist#migrating-from-mongojs) from mongojs too!

**Comment by xfg** [comment]
The supprort ```async/await``` must be within this package without external dependencies. I don't want to have the callback hell in my code.
