### ISSUE TITLE
Mongolab upgradation to 3.2 & its syntax compatability

### ISSUE THREAD

**Issue by senthamilan** [mafintosh/mongojs#325]
After Mongolab upgraded their version to 3.2, the general syntax for find collection is no more working with the library 'mongojs'. When contacted mongolab support, they say 'mongojs' library was not updated in accordance with their upgradation. Its terrible to see that entire system came standstill because of this upgradation issue and has to be sorted out as quickly as possible

**Comment by sorribas** [comment]
Hey @senthamilan, so sorry for this problem.

Can you put a specific example of what is failing for you? I'm trying a couple of finds in a mongolab 3.2 server and it seems to work. I think this might be solved by updating the driver, but I  want to have a clear example of what's going wrong.

**Comment by senthamilan** [comment]
Dear Sorribas,
Kindly refer below code which is working before mongolab 3.2 upgradation
"tbl_testcollection" is collection name and while querying object "docs_config" is null and error message in object "err_config"  is something like ""failed to parse: { find:}, projection: {}, slaveok: false }. unrecognized field 'slaveok' "
i didn't updated the driver, will test and let u know once i updated .

/******************************************************/
var mongojs = require('mongojs')
var SSCollections = mongojs('mongodb://username:password@ds012345.mlab.com:12345/db_test', [], { authMechanism : 'ScramSHA1' });


SSCollections.collection("tbl_testcollection").find({ "config_id": "1" },
    {}, {}).toArray(function (err_config, docs_config) {
    
    if(docs_config != null && docs_config.length > 0)
    var array = docs_config.map(function (item) {
        return item.config;
    });

    
});

**Comment by sorribas** [comment]
Which version of `mongojs` are you using? Similar queries are working for me with the latest mongojs release (`2.4.0`).

**Comment by senthamilan** [comment]
Dear sorribas,
Its working after updating the driver. It will be useful to send notification for updating the driver whenever third party apps was upgraded and the mongojs driver was updated accordingly.
Thanks

**Comment by sorribas** [comment]
Hey @senthamilan. Glad to hear it works now!

You can subscribe to the RSS feed of `mongojs` releases

https://github.com/mafintosh/mongojs/releases.atom

Or you can use some kind of RSS to email tool if you want to get notified when new versions of `mongojs` come out. I'm closing this issue now.
