### ISSUE TITLE
MongoDB 3.6 compatibility?

### ISSUE THREAD

**Issue by karanmartian** [mafintosh/mongojs#354]
Hi,
Some of my Mlab databases will be upgraded from 3.4 to 3.6. mongojs will be compatible as it is right without any changes with v3.6 of mongodb?

**Comment by sorribas** [comment]
Hi @karanmartian. I ran the test suite with Mongodb 3.6 and they all pass. So it seems to work.

**Comment by karanmartian** [comment]
Thanks so much @sorribas really appreciate it!
