### ISSUE TITLE
how to set remote connection to mongodb

### ISSUE THREAD

**Issue by KoldunMax** [mafintosh/mongojs#372]
i need set remote connection to MongoDB, but i need make it via [mongojs](https://www.npmjs.com/package/mongojs/v/0.9.2).

    var docdbconn = mongojs('mongodb+srv://mylogin:mypassword@cluster0-m1s1a.mongodb.net/nameofdatabase?retryWrites=true');

and usually i get next error:

    MongoError: failed to connect to server [cluster0-m1s1a.mongodb.net:27017] on first connect [MongoError: getaddrinfo ENOTFOUND cluster0-m1s1a.mongodb.net cluster0-m1s1a.mongodb.net:27017]

**Comment by novenix** [comment]
could you find a solution of this problem? i have it to

**Comment by novenix** [comment]
Could you fix the problem?, i have the same issue

**Comment by KoldunMax** [comment]
yes, i used another link ```mongodb://mylogin:<password>@cluster0-shard-00-00-m1s1a.mongodb.net:27017,cluster0-shard-00-01-m1s1a.mongodb.net:27017,cluster0-shard-00-02-m1s1a.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true``` for node.js 2.2.12 or later

**Comment by karanmartian** [comment]
> yes, i used another link `mongodb://mylogin:<password>@cluster0-shard-00-00-m1s1a.mongodb.net:27017,cluster0-shard-00-01-m1s1a.mongodb.net:27017,cluster0-shard-00-02-m1s1a.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true` for node.js 2.2.12 or later

Yes this other string works! so is that because mongojs does not support node 3 and above?
