### ISSUE TITLE
How do i show dbs, similar to shell "show dbs"

### ISSUE THREAD

**Issue by CityOnTheEdgeOfForever** [mafintosh/mongojs#373]
Hello,

I've spent many hours trying to run js code to show list of databases, much like the shell command "show dbs." I've tried it with mongodb, and I run into issues where database is null. So, trying it via mongojs.

How do i get a list of dbs names? documentation shows you can run commands like in mongo shell. how do i run "show dbs"

thanks.

**Comment by hamzaam100** [comment]
This is what worked for me:
```
const db = mongojs('db', ['collection']);

db.runCommand({ listDatabases: 1 }, function(err, result){
        const databases = result.databases;
        // your code
});
```
