### ISSUE TITLE
v2.6.0 up to v3.1.0 update operation error!

### ISSUE THREAD

**Issue by maomaoguo2017** [mafintosh/mongojs#384]
mongodb:v3.6.12
![image](https://user-images.githubusercontent.com/34433498/70712946-f469fd80-1d1f-11ea-8de2-057f6df4fb5a.png)
![image](https://user-images.githubusercontent.com/34433498/70712955-fd5acf00-1d1f-11ea-86fb-d43ed5fb9edc.png)
change mongojs to 2.6.0, is fine
![image](https://user-images.githubusercontent.com/34433498/70712989-0cda1800-1d20-11ea-8ff9-07bec57a92dd.png)
![image](https://user-images.githubusercontent.com/34433498/70713090-3b57f300-1d20-11ea-96e7-143847303cf9.png)

**Comment by maomaoguo2017** [comment]
i know when i write like:
```
mongodb.test.update({"_id":"5df233b78bb41822be706405"},{"$set":{"a":33}},{upsert:true}, function(err, ret){
       console.log('err:', err);
});
```
it's work fine. But in this way, it is not compatible with the old interface parameters.

**Comment by maomaoguo2017** [comment]
In the database version 3.6.12, this call is allowed
![image](https://user-images.githubusercontent.com/34433498/70714424-144ef080-1d23-11ea-830a-bd68268f8d7a.png)

**Comment by maomaoguo2017** [comment]
![image](https://user-images.githubusercontent.com/34433498/70716061-86750480-1d26-11ea-8db4-ad3b7c6a2b06.png)

![image](https://user-images.githubusercontent.com/34433498/70716034-76f5bb80-1d26-11ea-8087-fd094aa9c0b5.png)
![image](https://user-images.githubusercontent.com/34433498/70716075-9260c680-1d26-11ea-8492-72ce007fbf12.png)

**Comment by naugtur** [comment]
The official mongodb client library underneath is not accepting plain objects as input to update despite mongo docs suggesting update could accept them. I don't know which is correct but of code and docs disagree, code tend to win ;)

You need to switch to replaceOne.

**Comment by maomaoguo2017** [comment]
@naugtur thanks.
