### ISSUE TITLE
auth fails

### ISSUE THREAD

**Issue by GeoffreyPlitt** [mafintosh/mongojs#51]
Hi,

My connection string is:

root:s6m3ta7I9w711vCN2Xgz@margindev-geoffmaker-db-0.azva.dotcloud.net:40769/maker_ad_planner

I do:
mongojs = require 'mongojs');
db = mongojs(connection_string);
db.collection('stuff').find({}, function(err, results) {
  return log.info(err, results);
});

And I get:
2013-04-12 23:41:02.512] (info) { [MongoError: auth fails] name: 'MongoError', errmsg: 'auth fails', ok: 0 } undefined

What am I doing wrong?

**Comment by balachandertgm** [comment]
Hi,
when i use find method  i got auth error.

code:
var databaseUrl = "mongodb://root:mean@localhost:/mydb"; 
var collections = ["users", "reports"]
var mongojs = require('mongojs');
var db = mongojs("mydb",['mycollection']);


db.mycollection.find({sex: "female"},function(err, docs) {
    // docs is an array of all the documents in mycollection
	console.log(err);
	console.log(docs);
});

error:
mongodb\lib\mongodb\mongo_client.js:460
              throw err
                    ^
MongoError: auth failed
    at Object.toError (C:\Bitnami\meanstack-2.6.7-0\projects\mongojs\node_module
s\mongojs\node_modules\mongodb\lib\mongodb\utils.js:114:11)
    at C:\Bitnami\meanstack-2.6.7-0\projects\mongojs\node_modules\mongojs\node_m
odules\mongodb\lib\mongodb\db.js:1194:31
    at C:\Bitnami\meanstack-2.6.7-0\projects\mongojs\node_modules\mongojs\node_m
odules\mongodb\lib\mongodb\db.js:1903:9
    at Server.Base._callHandler (C:\Bitnami\meanstack-2.6.7-0\projects\mongojs\n
ode_modules\mongojs\node_modules\mongodb\lib\mongodb\connection\base.js:453:41)
    at C:\Bitnami\meanstack-2.6.7-0\projects\mongojs\node_modules\mongojs\node_m
odules\mongodb\lib\mongodb\connection\server.js:487:18
    at MongoReply.parseBody (C:\Bitnami\meanstack-2.6.7-0\projects\mongojs\node_
modules\mongojs\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js:68:5)
    at null.<anonymous> (C:\Bitnami\meanstack-2.6.7-0\projects\mongojs\node_modu
les\mongojs\node_modules\mongodb\lib\mongodb\connection\server.js:445:20)
    at emit (events.js:107:17)
    at null.<anonymous> (C:\Bitnami\meanstack-2.6.7-0\projects\mongojs\node_modu
les\mongojs\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:207:1
3)
    at emit (events.js:110:17)
