### ISSUE TITLE
how do  I do "show collections" in mongojs code?

### ISSUE THREAD

**Issue by xiaochunmei** [mafintosh/mongojs#54]
Mongo db shell support "show collections" to list all the collections of a database.
How do I do this in javascript using mongojs?

**Comment by AndrewKralovec** [comment]
db.getCollectionNames(function(err, colNames) {
  if (err) return  console.log(err);
  colNames.forEach(function(name) {
    console.log(name);
  });
});

This will just list the collections, which is already using inside the mongojs call // var db = mongojs(connectionString, [collections] 
So pointless. 
You will have to use mongodb  and then use the admin option 

 // Use the admin database for the operation
  var adminDb = db.admin();

  // List all the available databases
  adminDb.listDatabases(function(err, dbs) {
    assert.equal(null, err);
    assert.ok(dbs.databases.length > 0);
    console.log(dbs);
    db.close();
  });
});
