### ISSUE TITLE
open called multiple times with connect-mongo

### ISSUE THREAD

**Issue by aleiby** [mafintosh/mongojs#57]
I'm trying to use mongojs in conjunction with connect-mongo.  This was working fine several months ago, but I recently decided to blanket upgrade everything and am now running into problems.

``` javascript
var express = require('express')
  , mongojs = require('mongojs')
  , MongoStore = require('connect-mongo')(express);

var collections = ["users"];
var db = mongojs("db", collections);

var sessionStore = new MongoStore({ db: db });
```

The above complains about calling open twice.

> /home/ec2-user/server/node_modules/mongodb/lib/mongodb/connection/server.js:562
>         throw err;
>               ^
> Error: db object already connecting, open cannot be called multiple times
>     at Db.open (/home/ec2-user/server/node_modules/mongodb/lib/mongodb/db.js:224:11)
>     at /home/ec2-user/server/node_modules/mongojs/index.js:235:8
>     at apply (/home/ec2-user/server/node_modules/mongojs/node_modules/thunky/index.js:16:28)
>     at /home/ec2-user/server/node_modules/mongojs/node_modules/thunky/index.js:20:25
>     at /home/ec2-user/server/node_modules/mongojs/index.js:206:4
>     at /home/ec2-user/server/node_modules/mongodb/lib/mongodb/mongo_client.js:334:7
>     at /home/ec2-user/server/node_modules/mongodb/lib/mongodb/db.js:258:14
>     at null.<anonymous> (/home/ec2-user/server/node_modules/mongodb/lib/mongodb/connection/server.js:374:9)
>     at g (events.js:183:14)
>     at EventEmitter.emit (events.js:108:17)

Switching to `var sessionStore = new MongoStore({ db: "db" });` instead avoids the issue, but means having multiple connections open (which I'd like to avoid).

connect-mongo checks `db.openCalled` before calling open (which is `undefined` on the mongojs object).  I used to pass `db.client` to MongoStore's constructor, but that appears to have been removed.

Manually setting `db.openCalled = true;` avoids the exception, but introduces issues later on (as the variable is getting set on the wrapper and not the db itself).

**Comment by davidwieler** [comment]
I know this is old, but it still doesn't work.
The comment before closing doesn't work because of it needs to be a string:

`db: mongojs('database', ['sessions'])`

"Error: `db` option must be a string, array or a database instance."

I'm almost at the point of switching to mongoose
