### ISSUE TITLE
continueOnError / keepGoing Option

### ISSUE THREAD

**Issue by hamedabdy** [mafintosh/mongojs#58]
I was wondering if Mongojs does support the continueOnError or keepGoing options that come with native-mongo? 
If yes, how? an example would be appreciated. 
Thanks in advance.

**Comment by damienromito** [comment]
The problem now is : the param "docs" is equal to "null" when there is an error. How to get all inserted objects?

**Comment by hamedabdy** [comment]
When there is no error the `doc` param contains all your documents. (Please do correct me if I'm wrong)

**Comment by damienromito** [comment]
You're right, but in my case, I have errors cause I insert duplicated objects. I use the option {ordered:false} to not stop the insertion, but I cannot get all inserted object (cause I have one of several error). It's not possible to return object when the option "ordered" is setted to false?

**Comment by hamedabdy** [comment]
I think it's mostly like every time there is a duplicate key an error is thrown with its cause! Thus you should only get one document for each error!
