### ISSUE TITLE
Support for distinct?

### ISSUE THREAD

**Issue by metasansana** [mafintosh/mongojs#61]
The distinct() function allows me to create a list from a collection like so :
//Collection
{

  'country': 'Japan',
  'currency': 'yen'
}
...
db.currency.distinct({'country'}) // Gives me ['Japan', 'Canada', 'Trinidad & Tobago'].

Any plans on supporting it?

**Comment by alexbfree** [comment]
does it work with nested fields? I can get it to work with top level fields but field.subfield format seems not to be recognised....

**Comment by sorribas** [comment]
@alexbfree It is supported. You have to do something like this.

```js
db.pets.distinct('owener.name', function(err, names) {
  console.log(names);
})
```

**Comment by alexbfree** [comment]
Great, thanks. I don't know why it wasn't working for me before but it is now.

**Comment by soichih** [comment]
You have to do pass query between field name and cb now.

```
db.pets.distinct('owener.name', {}, function(err, names) {
  console.log(names);
})
```

**Comment by Mamta13** [comment]
Thank you so much soichih  i was struck on this for 2 days now.. thanks a lot
