### ISSUE TITLE
_id after insert() or save()

### ISSUE THREAD

**Issue by sthomas-github** [mafintosh/mongojs#86]
Can you point me to an example of insert() or save() which returns or immediately allows capture of the newly created _id field?  I've tried a number of things to no avail, and don't seem to be able to find an example.

Thanks,

Steve

**Comment by drasko** [comment]
I can not get this to work...

```
/** Save the device and check for errors */
devicesDb.save(req.body, function(err, device) {
    if (err)
        return next(err)
    console.log("+++ DEVICE: " + device._id);
});
```
logs on the console:
```
+++ DEVICE: undefined
```

**Comment by drasko** [comment]
Found it - I had to add:
```
-H 'Content-Type: application/json' 
```
to `curl` requests.
